# This file was generated by GoReleaser. DO NOT EDIT.
cask "dogstatsd-local" do
  version "1.0.10"

  on_macos do
    on_intel do
      sha256 "9f6451a2505ae3f5b7ff72b423d847b1ee602e512d1956ec0e3d8f602d6a4a14"
      url "https://github.com/mroyme/dogstatsd-local/releases/download/v#{version}/dogstatsd-local_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "553b84792603e3230648a3eef72579d39b0820358186db902151d92b93898a03"
      url "https://github.com/mroyme/dogstatsd-local/releases/download/v#{version}/dogstatsd-local_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "852e77566e034d8ae4b588e201f7deeb458d96a8c5d7a01e851ac448d2aefec7"
      url "https://github.com/mroyme/dogstatsd-local/releases/download/v#{version}/dogstatsd-local_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "947199c7b0037bccca2194c6672c41badea2d86f34a5f8535c9eef37c5c05604"
      url "https://github.com/mroyme/dogstatsd-local/releases/download/v#{version}/dogstatsd-local_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dogstatsd-local"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dogstatsd-local"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dogstatsd-local"]
    end
  end

  # No zap stanza required

end
