# This file was generated by GoReleaser. DO NOT EDIT.
cask "dogstatsd-local" do
  version "1.0.12"

  on_macos do
    on_intel do
      sha256 "8448427fc606b4d7afdc019aeb0ffbe0e852e434a687338c27a7884529c38451"
      url "https://github.com/mroyme/dogstatsd-local/releases/download/v#{version}/dogstatsd-local_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/mroyme/dogstatsd-local/"
    end
    on_arm do
      sha256 "bce7c4a8dfc8a58a235cc0b1ad686046e790065cd6846631e806dd1e9dc94631"
      url "https://github.com/mroyme/dogstatsd-local/releases/download/v#{version}/dogstatsd-local_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/mroyme/dogstatsd-local/"
    end
  end

  on_linux do
    on_intel do
      sha256 "da592b749e13dbbe74ea4bd1328153f40ff8cc5c463232350a7f585502e787e2"
      url "https://github.com/mroyme/dogstatsd-local/releases/download/v#{version}/dogstatsd-local_#{version}_linux_amd64.tar.gz",
        verified: "github.com/mroyme/dogstatsd-local/"
    end
    on_arm do
      sha256 "0eefdb2df052c8dd6fe835d92e45aa88b8161195905ad8b53bbcd26b0b975c62"
      url "https://github.com/mroyme/dogstatsd-local/releases/download/v#{version}/dogstatsd-local_#{version}_linux_arm64.tar.gz",
        verified: "github.com/mroyme/dogstatsd-local/"
    end
  end

  name "dogstatsd-local"
  desc "A local DogStatsD protocol inspector for debugging metrics, service checks, and events"
  homepage "https://mroyme.github.io/dogstatsd-local/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dogstatsd-local"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dogstatsd-local"]
    end
  end

  # No zap stanza required

end
