# This file was generated by GoReleaser. DO NOT EDIT.
cask "dogstatsd-local" do
  version "1.0.11"

  on_macos do
    on_intel do
      sha256 "c5d2fcbd14cc353df65e07d5296bae2ab91b941c23cd6448e5291ef8bcc7eda5"
      url "https://github.com/mroyme/dogstatsd-local/releases/download/v#{version}/dogstatsd-local_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "440eb5fe8f65967902679f763ed114fe1c0ac7099d71c77e959ce6b21810714d"
      url "https://github.com/mroyme/dogstatsd-local/releases/download/v#{version}/dogstatsd-local_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "06538398ced120c435ae6de912f761c2a74d33c881e653b7ef26e17e663886f2"
      url "https://github.com/mroyme/dogstatsd-local/releases/download/v#{version}/dogstatsd-local_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0d8f96e6f07a2ea2d752337dac2c67a493716461b26ef837bb6a1be2766a1577"
      url "https://github.com/mroyme/dogstatsd-local/releases/download/v#{version}/dogstatsd-local_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dogstatsd-local"
  desc "A local DogStatsD protocol inspector for debugging metrics, service checks, and events"
  homepage "https://mroyme.github.io/dogstatsd-local/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dogstatsd-local"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dogstatsd-local"]
    end
  end

  # No zap stanza required

end
